Add wrapper
Tiime-Software/Factur-X pull request #26
Opened 2023-05-04 11:45 UTC by AurelienPillevesse

Add wrapper

2023-05-04 12:44 UTC, Lucas-Gerard commented on src/FacturX.php
> +    private \Atgp\FacturX\Facturx $instanceFacturxLibrary;
```suggestion
    private \Atgp\FacturX\Facturx $facturXManager;
```

?

2023-05-04 15:17 UTC, rflavien commented on src/FacturX.php
> +    public function getXmlContent(): ?string
```suggestion
    public function getXmlContent(): string
```
redondant avec extractXmlFromPdf, je garderais uniquement la méthode getXmlContent() (ou juste getXml())

2023-05-04 15:17 UTC, rflavien commented on src/FacturX.php
> +    public function generate(array $additionalAttachments = [], bool $addFacturxLogo = true): string
```suggestion
    public function generate(array $additionalAttachments = [], bool $addFacturxLogo = true): string
```
redondant avec getPDFContent.

Pour qu'on comprenne mieux mes commentaires, je vois plus une API comme : 
```php
class FacturX {
  public function __construct(string $pdfContent, ?string $xmlContent = null);
  public function getXmlContent(): string;
  public function getPdfContent(): string;
  public function addFacturxLogo(): void;
  public function addAttachments(iterable $additionalAttachments):void;
}
```

2023-05-05 13:26 UTC, rflavien requested changes

2023-05-05 13:26 UTC, rflavien commented on src/FacturX.php
> +        }
ca me semble plus optimisé de faire la génération uniquement lorsqu'on appel la méthode `getPdfContent()`

Exemple du use case où on souhaite uniquement ajouter un logo :
```php
$f = new FacturX($pdf);
$f->addFacturexLogo();
$f->getPdfContent();
```
Idem pour les Attachements, les méthodes d'ajout peuvent se contenter de conserver l'info dans l'état de l'objet et la méthode getPdfContent génère au moment voulu en fonction de cet état.

2023-05-09 07:28 UTC, aurelienp-pdp commented on src/FacturX.php
> +        }
J'ai fait évolué la librairie, je te laisse me faire un retour

2023-05-10 06:59 UTC, rflavien approved these changes

2023-05-10 07:47 UTC, Lucas-Gerard approved these changes

2023-05-10 07:47 UTC, merged